server:
  port: ${EUREKA_PORT:8761}

spring:
  application:
    name: ${EUREKA_SERVICE_NAME:eureka-discovery-service}

eureka:
  server:
    enable-self-preservation: true
    renewalPercentThreshold: 0.33 # This is only if one server is started
    wait-time-in-ms-when-sync-empty: 1000
  instance:
    hostname: ${EUREKA_HOST:localhost}
    instance-id: ${spring.application.name}:${instanceId:${random.value}}
  client:
    registerWithEureka: false
    fetchRegistry: false
  serviceUrl:
    defaultZone: ${EUREKA_URI:http://${eureka.instance.hostname}:${server.port}/eureka/}

logging:
  level:
    com.netflix.eureka: OFF
    com.netflix.discovery: OFF