server:
  port: 0

spring:
  application:
    name: demo-rest-controller-app

eureka:
  instance:
    instance-id: ${spring.application.name}:${DEMO_REST_CONTROLLER_APP_INSTANCE_ID:${random.value}}
  serviceUrl:
    defaultZone: ${EUREKA_URI:http://${eureka.serviceHost}:${eureka.servicePort:8761}/eureka}
  # Custom properties
  serviceHost: ${EUREKA_HOST:localhost}
  servicePort: ${EUREKA_PORT:8761}