server:
  port: 8088

spring:
  application:
    name: logosflow-gateway
  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"


      routes:
        - id: demo-rest-controller-app
          uri: lb://demo-rest-controller-app
          predicates:
            - Path=/demo/controller/rest/resources/timed-resource
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
        - id: libraries-server
          uri: lb://libraries-server
          predicates:
            - Path=/resources/libraries/**
            - Method=GET
          filters:
            - RemoveRequestHeader=Cookie
        - id: spa-demo-app
          uri: lb://spa-demo-app
          predicates:
            - Path=/index.html,/,/authcodeReader.html,/scripts/**
            - Method=GET

eureka:
  instance:
    instance-id: ${spring.application.name}:${LOGOSFLOW_GATEWAY_INSTANCE_ID:${random.value}}
  serviceUrl:
    defaultZone: ${EUREKA_URI:http://${eureka.serviceHost}:${eureka.servicePort:8761}/eureka}
  # Custom properties
  serviceHost: ${EUREKA_HOST:localhost}
  servicePort: ${EUREKA_PORT:8761}