@startuml
class OidcPkceUtils {
  +{static} oidcClientConfiguration
  +{static} oAuth2login()
  +{static} oAuth2logout()
  +{static} forceLogin()
  +{static} onOauth2Authorize()
  +{static} getAccessToken()
}

class OidcClientConfiguration{
  + authorizationEndpoint
  + tokenEndpoint
  + tokenEndpoint
  + userInfoEndpoint
  + endSessionEndpoint
  + check_session_iframe
  + session_state
  + clientId
  + redirectUri
  + scope
  + responseType
  + pkce
}

class Oauth2LoginLogoutManager {

  +{static} forceLogin(scopes)
  +{static} logout()
  -{static} clearOauth2StoredData()
  ~{static} login()
  ~{static} getAccessToken(scopes)
  -{static} waitUntilLoginIsSuccessful()
  -{static} listenRemoteLogout()
  -{static} refreshAndGetAccessToken(scopes)
}

class AuthorizationUriBuilder {
  +{static} buildUriFor(config, state, codeChallenge, scopes)
}

class PageStateStorage {
  +storeOauth2State(state)
  +retrieveOauth2State()
  +clear()
}

class PageStateGenerator {
+generateState()
+generateRandomString(length)
}

class PkceCodeChallengeVerifierGenerator {
+generateCodeVerifier()
+generateCodeChallengeValue(codeVerifier)
}

class PkceCodeChallengeVerifierStorage {
+storeOauth2PkceCodeChallenge(codeChallenge)
+storePkceCodeVerifier(codeVerifier)
+retrievePkceCodeVerifier()
+retrievePkceCodeChallenge()
+clearPair()
}

class RedirectUserToAuthorization {
+redirectToUrl(authorizationUrl)
}

class OnOAuth2AuthorizedHandler {
+handle(state, authCode)
}

class OidcTokenExchanger {
+{static} exchangeCodeOnOidcTokens(authCode)
-{static} exchangeAuthCodeOnTokens(authCode, codeVerifier)
-{static} cleanHistoryForCodeExchange()
+{static} requestRefreshedOidcTokens(refreshToken)
}

class OidcTokensStorage {
+storeOidcTokens(oidcTokens)
+getAccessToken()
+getRefreshToken()
+getIdToken()
+getScopes()
+getSessionState()
+clear()
}

class TokenParser {
+parseJwtToJsonPayloadAsString(jwtTokenAsJwtString)
+parseJwtPayloadStringToObject(jwtPayloadPartAsJson)
+getExpirationTimeUtc(jwtTokenAsJwtString)
}

class AccesTokenManager {
+{static} isAuthenticationSuccessful()
+{static} isAccessTokenValid(accessToken, scopes)

}

OidcPkceUtils --> Oauth2LoginLogoutManager
OidcPkceUtils --> OnOAuth2AuthorizedHandler: uses for onOauth2Authorize >
OidcPkceUtils --> OidcClientConfiguration
Oauth2LoginLogoutManager --> AuthorizationUriBuilder: uses for forceLogin, Login >
Oauth2LoginLogoutManager --> AccesTokenManager: uses for getAccessToken, waitUntilLoginIsSuccessful, login >
Oauth2LoginLogoutManager --> OidcTokenExchanger: uses for refreshAndGetAccessToken >
Oauth2LoginLogoutManager --> PageStateStorage: uses for forceLogin, clearOauth2StoredData >
Oauth2LoginLogoutManager --> PageStateGenerator
Oauth2LoginLogoutManager --> PkceCodeChallengeVerifierGenerator
Oauth2LoginLogoutManager --> PkceCodeChallengeVerifierStorage
Oauth2LoginLogoutManager --> RedirectUserToAuthorization
Oauth2LoginLogoutManager --> OnOAuth2AuthorizedHandler
OnOAuth2AuthorizedHandler --> OidcTokenExchanger
AccesTokenManager --> PageStateStorage: uses for isAuthenticationSuccessful >
AccesTokenManager --> OidcTokensStorage: uses for isAuthenticationSuccessful(), isAccessTokenValid >
AccesTokenManager --> OidcClientConfiguration

OidcTokenExchanger --> TokenParser
OidcTokensStorage --> TokenParser
OnOAuth2AuthorizedHandler --> OidcTokensStorage
@enduml
