@startuml
actor User as user
participant "index.html/authcodeReader.html" as html
participant "OidcPkceUtils" as utils
participant "Oauth2LoginLogoutManager" as loginManager
participant "AuthorizationUriBuilder" as uriBuilder
participant "PageStateStorage" as pageState
participant "PkceCodeChallengeVerifierGenerator" as pkceGen
participant "RedirectUserToAuthorization" as redirect
participant "OnOAuth2AuthorizedHandler" as authHandler
participant "AccesTokenManager" as tokenManager
participant "OidcTokensStorage" as tokenStorage

user -> html: Access Application
html -> utils: oAuth2login()
utils -> loginManager: login()
loginManager -> pageState: storeOauth2State(state)
loginManager -> pkceGen: generateCodeVerifier()
loginManager -> uriBuilder: buildUriFor(config, state, codeChallenge, scopes)
uriBuilder -> loginManager: authorizationUrl
loginManager -> redirect: redirectToUrl(authorizationUrl)
redirect -> browser: Open Authorization URL
browser -> user: Login and Authorize
browser -> html: Redirect with Authorization Code
html -> utils: onOauth2Authorize(state, code)
utils -> authHandler: handle(state, authCode, dialogWindow)
authHandler -> tokenManager: exchangeCodeOnOidcTokens(authCode)
tokenManager -> tokenStorage: storeOidcTokens(oidcTokens)
authHandler -> user: Close Authorization Dialog
@enduml
